### ISSUE TITLE
Add a distributed bugtracker

### ISSUE THREAD

**Issue by chickenkiller** [jeremyz/ffi-efl#2]
Done, see here:

chickenkiller/ffi-efl@2bb5722a728bf043d76a4e0aaf7582048c4f8e11

**Comment by chickenkiller** [comment]
I was wondering whether to puts ditz in a separate branch, and I eventually decided it was overhead and that we would prefer having the bugs list always in sync with the code, so I checked-in ditz in the master branch.

I'm not against using a 'ditz' or 'bugs' branch, but in that case I suggest we put _only_ the ditz-related files in it, as suggested here: http://ditz.rubyforge.org/PLUGINS.txt (git-sync section).

What do you think?

**Comment by jeremyz** [comment]
I think you did right. I find it important to keep issues in sync with the code
