### ISSUE TITLE
Events from ruby?

### ISSUE THREAD

**Issue by mhanne** [jeremyz/ffi-efl#3]
Hi,

I'd like to build a simple jabber client, using a ruby library for the xmpp side. 

For the whole weekend, I've been trying to change the state of the UI triggered by an "external" event from ruby, but couldn't for the life of me figure out how to do that reliably.
Tried like half a dozen completely different ways, some looked promising at first, but eventually everything just starts to crash/hang/segfault randomly, and apparently I'm a naughty programmer :P

Before I start spamming you with broken code, is that (currently) possible at all? What would be the best way to do it?
(I've tried so many combinations of threads/timers/thread_safe_async() and different methods of generating the event, that i wouldn't know which one to post .. even tried talking through fd's with no luck)

**Comment by jeremyz** [comment]
Hi,
did you try with ecore_pipe, it seems to be the way according to ecore_thread doc.

https://gist.github.com/4265607

**Comment by mhanne** [comment]
Ah, nice. That works really well, thank you! :)
