### ISSUE TITLE
genruby.rb / Function not found

### ISSUE THREAD

**Issue by mhanne** [jeremyz/ffi-efl#5]
Using the efl built with install-efl.sh I got genruby.rb to run.

But I had to add these types
 'Emotion_Aspect' => ':pointer',
 'Emotion_Event' => ':pointer',
 'Emotion_Meta_Info' => ':pointer',
 'Emotion_Vis' => ':pointer',

And remove Eeze_Disk.h from the libs.
(./configure shows "eeze_disk_ls" to be enabled, but there's no header file.)

Also, I had to remove the ECORE_EVAS_EXTN_CLIENT_ADD/DEL variables from ecore_evas.rb, both with a regular `gem install ffi-efl` and after running genruby.rb.

Are these things specfic to my setup (on debian wheezy), or did I miss anything?

**Comment by jeremyz** [comment]
Hi,
install-efl.sh is not uptodate, it fetches efl 1.7.1, current is 1.7.5
preferably use [efl-release-build.sh](https://github.com/jeremyz/bin/blob/master/efl-release-build.sh) as specified in [README](https://github.com/jeremyz/ffi-efl/blob/master/README.md)

the scripts in tools are there to ease my maintenance job, but saddly not everything is automated,
btw you should not need to regenerate the bindings.

the above should run out of the box:
LD_LIBRARY_PATH=/opt/efl-stable/lib ./tools/check_loading
LD_LIBRARY_PATH=/opt/efl-stable/lib ruby -I lib ./test/test_elm_win.rb
LD_LIBRARY_PATH=/opt/efl-stable/lib ruby -I lib ./test/test_edje.rb
...

**Comment by jeremyz** [comment]
I've updated install-efl.sh

**Comment by mhanne** [comment]
Ah, that explains it, thanks!
Now all examples work without changing anything in lib/ :)

The install-efl.sh script still needed two little tweaks (a99d63db) but efl-release-build.sh worked as it is.
